name: Destroy env

on:
  workflow_dispatch:
    inputs:
      github_run_number:
        type: string
        required: true
        description: Enter the github run number of which env is created

jobs:
  destroy-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v2.0
      - name: "hello"
        env:
          GIT_NUMBER: ${{ inputs.github_run_number }}
        run: echo $GIT_NUMBER
