name: dsync services

on:
  push:
    branches:
      - master
      - 'SP/**'
      - 'HF/**'
      - company_release
      - 'GOOGLEDOCS**'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Enter the Commit Message
        required: true
env:
  SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
  GITHUB_EVENT: ${{ github.event_name }}
  BRANCH_NAME: ${{ github.ref_name }}


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [ build , source_clear, e2e_tests ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: '**/setup.py'

      - name: Run ${{ matrix.stage }}
        run: |
          echo "${{ github.event_name }}"
          echo "hello deploy release"
          bash ci/run.sh

  Release:
    if:  ${{ ( startsWith(github.ref_name, 'HF/')  || startsWith(github.ref_name, 'SP/') || github.ref_name == 'master' )  &&
         contains(github.event.head_commit.message, '[trigger release]') || inputs.commitMessage == 'release'  &&
         github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Run Script
        run: |
          echo "${{ github.event_name }}"
          echo "hello deploy release"
          bash _ci/run.sh


  Company-Release:
    if: github.ref_name == 'company_release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Run Script
        run: |
          echo "hello deploy release"