name: dsync services

on:
  push:
    branches:
      - omkar
      - master
      - 'SP/**'
      - 'HF/**'
      - company_release
      - 'GOOGLEDOCS**'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cluster_operation:
      description:  env to be created using
      type: choice
      required: true
      options:
        - GITHUB_NUMBER
        - STATIC
env:
  GITHUB_EVENT: ${{ github.event_name }}
  BRANCH_NAME: ${{ github.ref_name }}


jobs:
  pipeline:
    runs-on: macos-11
    steps:
      - name: Checkout code a
        uses: actions/checkout@v2
      
      - name: install Java 18
        run: sh ci/install_java_18.sh
