name: dsync services

on:
  push:
    branches:
      - omkar
      - master
      - 'SP/**'
      - 'HF/**'
      - company_release
      - 'GOOGLEDOCS**'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Enter the Commit Message
        required: true
env:
  SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
  GITHUB_EVENT: ${{ github.event_name }}
  BRANCH_NAME: ${{ github.ref_name }}


jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check last commit date
        id: commit_date
        run: echo "::set-output name=date::$(git log --format=%cd --date=format:%Y-%m-%d --max-count=1)"

      - name: Run pipeline if there was a commit this week
        if: ${{ steps.commit_date.outputs.date && steps.commit_date.outputs.date != '' && steps.commit_date.outputs.date != github.event.scheduled_time.substring(0, 10) && github.ref == 'refs/heads/main' }}
        run: |
          # Run your pipeline commands here
          echo "Running the pipeline..."
