name: dsync services

on:
  push:
    branches:
      - omkar
      - master
      - 'SP/**'
      - 'HF/**'
      - company_release
      - 'GOOGLEDOCS**'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Enter the Commit Message
        required: true
env:
  SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
  GITHUB_EVENT: ${{ github.event_name }}
  BRANCH_NAME: ${{ github.ref_name }}


jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code a
        uses: actions/checkout@v2
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
