name: dsync services

on:
  push:
    branches:
      - omkar
      - master
      - 'SP/**'
      - 'HF/**'
      - company_release
      - 'GOOGLEDOCS**'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      OM:
        description: the desired NAME 
        type: choice
        required: true
        options:
          - ABC
          - DC
          - AS
        default: ABC
env:
  GITHUB_EVENT: ${{ github.event_name }}
  BRANCH_NAME: ${{ github.ref_name }}


jobs:
  pipeline:
    runs-on: macos-11
    steps:
      - name: Checkout code a
        uses: actions/checkout@v2
      
      - name: install Java 18
        run: sh ci/install_java_18.sh
